name: marketcast-app

services:
  # Database PostgreSQL
  db:
    image: postgres:15
    container_name: marketcast_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-marketcast_dw}
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - marketcast_network

  # Adminer
  adminer:
    image: adminer
    container_name: marketcast_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - marketcast_network

  # MLflow
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    container_name: marketcast_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    networks:
      - marketcast_network

# Definisi Network diletakkan di paling bawah, sejajar dengan services
networks:
  marketcast_network:
    name: marketcast_network
    driver: bridge