FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow==2.13.0 psycopg2-binary boto3

# Port default MLflow UI
EXPOSE 5000

# Simpan artifacts & backend di /mlflow
RUN mkdir -p /mlflow/artifacts

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--default-artifact-root", "mlflow-artifacts:/artifacts", \
     "--artifacts-destination", "/mlflow/artifacts", \
     "--serve-artifacts"]