name: Daily Siskaperbapo Scraper

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip             # mempercepat instalasi dependencies dengan caching pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Run Daily Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python src/data/daily_scraper.py